---
logging:
  level: DEBUG
  log_dir: '../../tmp/reemission'
  log_filename: reemission.log
  mode: w # w for writing and a for append
latex:
  compiler: pdflatex # pdflatex, latexmk, default
  clean_tex: True
  compilations: 2
demo_data:
  dam_db:
    url: ""
    folder: "../../examples/demo/dams_shape"
    file: "demo_dams.shp"
  delineations:
    url: ""
    folder: "../../examples/demo/delinations"
    file: ""
...
