# Parameters of HEET tabular data output 
[tab_data]
    # Mandatory fields required for generating input file(s) to RE-EMISSION
    mandatory_fields = [
        "id", "c_area_km2", "c_biome", "c_climate_zone", 'c_landcover_0', 
        'c_landcover_1', 'c_landcover_2', 'c_landcover_3', 'c_landcover_4', 
        'c_landcover_5', 'c_landcover_6', 'c_landcover_7', 'c_landcover_8', 
        "c_mar_mm",  "c_map_mm", "c_masm_mm", "c_mean_olsen", "c_mean_slope_pc",
        "c_mpet_mm", "n_population", "c_soil_type", "dam_height", "dam_lat", 
        "dam_lon", "future_dam_model", "ms_length", "name", "r_area_km2",
        'r_landcover_bysoil_0', 'r_landcover_bysoil_1', 'r_landcover_bysoil_2',
        'r_landcover_bysoil_3', 'r_landcover_bysoil_4', 'r_landcover_bysoil_5',
        'r_landcover_bysoil_6', 'r_landcover_bysoil_7', 'r_landcover_bysoil_8',
        'r_landcover_bysoil_9', 'r_landcover_bysoil_10',
        'r_landcover_bysoil_11', 'r_landcover_bysoil_12',
        'r_landcover_bysoil_13', 'r_landcover_bysoil_14',
        'r_landcover_bysoil_15', 'r_landcover_bysoil_16',
        'r_landcover_bysoil_17', 'r_landcover_bysoil_18',
        'r_landcover_bysoil_19', 'r_landcover_bysoil_20',
        'r_landcover_bysoil_21', 'r_landcover_bysoil_22',
        'r_landcover_bysoil_23', 'r_landcover_bysoil_24',
        'r_landcover_bysoil_25', 'r_landcover_bysoil_26', 
        "r_maximum_depth_m", "r_mean_annual_windspeed",  "r_mean_depth_m",
        "t_dam_height", 'r_mean_temp_1', 'r_mean_temp_2', 'r_mean_temp_3', 
        'r_mean_temp_4', 'r_mean_temp_5', 'r_mean_temp_6', 'r_mean_temp_7', 
        'r_mean_temp_8', 'r_mean_temp_9', 'r_mean_temp_10', 'r_mean_temp_11', 
        'r_mean_temp_12', "r_mghr_all_kwhperm2perday", 
        "r_mghr_may_sept_kwhperm2perday", "r_mghr_nov_mar_kwhperm2perday",
        "r_msocs_kgperm2", "r_volume_m3", "year_commissioned"]
    # Alternative fields, e.g. fields containing outputs required for calculating
    # gas emissions that are derived from alternative data sources
    alternative_fields = [
        "c_mad_m3_pers", "c_map_mm_alt1", "c_mar_mm_alt1", "c_mar_mm_alt2",
        "c_masm_mm_alt1", "c_mmr_mm_alt2", "c_mpet_mm_alt1",
        "r_mghr_all_kwhperm2perday_alt1", "r_mghr_may_sept_kwhperm2perday_alt1",
        "r_mghr_nov_mar_kwhperm2perday_alt1"]
    # Fields that are currently not used for derivation of RE-EMISSION inputs
    # but may be used for ghg emission calculations with other models
    unused_inputs = [
        "c_msbdod_kgperdm3", "c_msnc_gperkg", "c_msocc_gperkg", "c_msocc_perc", 
        "c_msocs_kgperm2", "c_mswc_molperkg", "c_mswn_molperkg", 
        "r_maximum_depth_m_alt1", "r_maximum_depth_m_alt2",
        "r_msbdod_kgperdm3", "r_msnc_gperkg", "r_msocc_gperkg", "r_msocc_perc"]
[shp_concat]
[shp_concat.catchments]
    pattern = "C_*.shp"
    filename = "catchments.shp"
[shp_concat.flooded_rivers]
    pattern = "MS_*.shp"
    filename = "rivers.shp"
[shp_concat.dams]
    pattern = "PS_*.shp"
    filename = "dams.shp"
[shp_concat.reservoirs]
    pattern = "R_*.shp"
    filename = "reservoirs.shp"
[shp_concat.catchments_minus_reservoirs]
    pattern = "N_*.shp"
    filename = "catchments_minus_reservoirs.shp"
[shp_output]
[shp_output.catchments]
    # Mapping between index of the tabular data and index of the original shp
    match_keys = ["id", "id"]
    # Fields to be copied from the tabular data to the shape file
    fields = ["c_mar_mm", "c_area_km2", "n_population", "c_mean_slope_pc",
              "c_map_mm", "c_mpet_mm", "c_masm_mm", "c_biome", "c_soil_type",
              "c_mean_olsen", "ms_length"]
[shp_output.dams]
    # Mapping between index of the tabular data and index of the original shp
    match_keys = ["id", "id"]
    # Fields to be copied from the tabular data to the shape file
    fields = ["t_dam_height", "dam_lat", "dam_lon"]
[shp_output.reservoirs]
    # Mapping between index of the tabular data and index of the original shp
    match_keys = ["id", "id"]
    # Fields to be copied from the tabular data to the shape file
    fields = ["r_volume_m3","r_area_km2", "r_maximum_depth_m", "r_mean_depth_m",
              "r_msocs_kgperm2", "r_mghr_all_kwhperm2perday",
              "r_mghr_may_sept_kwhperm2perday",
              "r_mghr_nov_mar_kwhperm2perday", "r_mean_annual_windspeed",
              "c_mar_mm", "c_area_km2", "n_population", "c_mean_slope_pc",
              "c_map_mm", "c_mpet_mm", "c_masm_mm", "c_biome", "c_soil_type",
              "c_mean_olsen", "ms_length"]
