---
# Inputs to save for reporting of results
coordinates:
  include: True
  name: "Reservoir coordinates (lat/lon)"
  long_description: ""
  unit: "deg"
  unit_latex: "$^o$"
id:
  include: True
  name: "Reservoir ID"
  long_description: ""
  unit: ""
  unit_latex: ""
type:
  include: True
  name: "Reservoir type"
  long_description: ""
  unit: ""
  unit_latex: ""
monthly_temps:
  include: True
  name: "Monthly Temperatures"
  long_description: ""
  unit: "deg C"
  unit_latex: "$^o$C"
biogenic_factors:
  include: True
  name: "Biogenic factors"
  long_description: "Biome, Climate, Soil Type, Treatment Factor, Landuse Intensity"
  unit: ""
  unit_latex: ""
year_profile:
  include: True
  name: "Year vector for emission profiles"
  long_description: "List of years for which emission profiles are calculated"
  unit: "yr"
  unit_latex: "yr"
gasses:
  include: True
  name: "Calculated gas emissions"
  long_description: "List of gasses included in GHG emission calculations"
  unit: "-"
  unit_latex: "-"
catchment_inputs:
  include: True
  name: "Inputs for catchment-level process calculations"
  long_description: ""
  var_dict:
    runoff:
      name: "Annual runoff"
      unit: "mm/year"
      unit_latex: "mm/year"
    area:
      name: "Catchment area"
      unit: "km2"
      unit_latex: "km$^2$"
    riv_length:
      name: "Length of inundated river"
      unit: "km"
      unit_latex: "km"
    population:
      name: "Population"
      unit: "capita"
      unit_latex: "capita"
    area_fractions:
      name: "Area fractions"
      unit: "-"
      unit_latex: "-"
    slope:
      name: "Mean catchment slope"
      unit: "%"
      unit_latex: "\\%"
    precip:
      name: "Mean annual precipitation"
      unit: "mm/year"
      unit_latex: "mm/year"
    etransp:
      name: "Mean annual evapotranspiration"
      unit: "mm/year"
      unit_latex: "mm/year"
    soil_wetness:
      name: "Soil wetness"
      unit: "mm over profile"
      unit_latex: "mm over profile"
    mean_olsen:
      name: "Soil Olsen P content"
      unit: "kgP/ha"
      unit_latex: "kgP ha$^{-1}$"
reservoir_inputs:
  include: True
  name: "Inputs for reservoir-level process calculations"
  long_description: ""
  var_dict:
    volume:
      name: "Reservoir volume"
      unit: "m3"
      unit_latex: "m$^3$"
    area:
      name: "Reservoir area"
      unit: "km2"
      unit_latex: "km$^2$"
    max_depth:
      name: "Maximum reservoir depth"
      unit: "m"
      unit_latex: "m"
    mean_depth:
      name: "Mean reservoir depth"
      unit: "m"
      unit_latex: "m"
    area_fractions:
      name: "Inundated area fractions"
      unit: "-"
      unit_latex: "-"
    soil_carbon:
      name: "Soil carbon in inundated area"
      unit: "kgC/m2"
      unit_latex: "kgC m$^{-2}$"
    mean_radiance:
      name: "Mean monthly horizontal radiance"
      unit: "kWh/m2/d"
      unit_latex: "kWh m$^{-2}$ d$^{-1}$"
    mean_radiance_may_sept:
      name: "Mean monthly horizontal radiance: May - Sept"
      unit: "kWh/m2/d"
      unit_latex: "kWh m$^{-2}$ d$^{-1}$"
    mean_radiance_nov_mar:
      name: "Mean monthly horizontal radiance: Nov - Mar"
      unit: "kWh/m2/d"
      unit_latex: "kWh m$^{-2}$ d$^{-1}$"
    mean_monthly_windspeed:
      name: "Mean monthly wind speed"
      unit: "m/s"
      unit_latex: "m s$^{-1}$"
    water_intake_depth:
      name: "Water intake depth below surface"
      unit: "m"
      unit_latex: "m"

print_long_descriptions: False
...
