---
# Inputs to calculate and save for reporting of results
monthly_temps:
  include: True
  name: "Monthly Temperatures"
  long_description: ""
  unit: "deg C"
  unit_latex: "$^o$C"
biogenic_factors:
  include: True
  name: "Biogenic factors"
  long_description: "Biome, Climate, Soil Type, Treatment Factor, Landuse Intensity"
  unit: ""
  unit_latex: ""
year_profile:
  include: True
  name: "Year vector for emission profiles"
  long_description: "List of years for which emission profiles are calculated"
  unit: "yr"
  unit_latex: "yr"
gasses:
  include: True
  name: "Calculated gas emissions"
  long_description: "List of gasses included in GHG emission calculations"
  unit: "-"
  unit_latex: "-"
catchment_inputs:
  include: True
  name: "Inputs for catchment-level process calculations"
  long_description: ""
  var_dict:
    runoff:
      name: "Annual runoff"
      unit: "mm/year"
      unit_latex: "mm/year"
    area:
      name: "Catchment area"
      unit: "ha"
      unit_latex: "ha"
    population:
      name: "Population"
      unit: "capita"
      unit_latex: "capita"
    area_fractions:
      name: "Area fractions"
      unit: "-"
      unit_latex: "-"
    slope:
      name: "Mean catchment slope"
      unit: "%"
      unit_latex: "\\%"
    precip:
      name: "Mean annual precipitation"
      unit: "mm/year"
      unit_latex: "mm/year"
    etransp:
      name: "Mean annual evapotranspiration"
      unit: "mm/year"
      unit_latex: "mm/year"
    soil_wetness:
      name: "Soil wetness"
      unit: "mm over profile"
      unit_latex: "mm over profile"
reservoir_inputs:
  include: True
  name: "Inputs for reservoir-level process calculations"
  long_description: ""
  var_dict:
    volume:
      name: "Reservoir volume"
      unit: "m3"
      unit_latex: "m$^3$"
    area:
      name: "Reservoir area"
      unit: "km2"
      unit_latex: "km$^2$"
    max_depth:
      name: "Maximum reservoir depth"
      unit: "m"
      unit_latex: "m"
    mean_depth:
      name: "Mean reservoir depth"
      unit: "m"
      unit_latex: "m"
    area_fractions:
      name: "Inundated area fractions"
      unit: "-"
      unit_latex: "-"
    soil_carbon:
      name: "Soil carbon in inundated area"
      unit: "kg/m2"
      unit_latex: "kg m$^{-2}$"

print_long_descriptions: False
...
