---
# Parameters included in reporting of results
# GWP Factors (for all emissions)
parameters:
  # GWP Factors (for all emissions)
  gwp100:
    include: True
    name: "Global Warming Potential for a 100-year timescale"
    name_latex: "Global Warming Potential for a 100-year timescale"
    unit: "-"
    unit_latex: "-"
    long_description: ""
  # Conversion factors to gCO2eq m-2 yr-1
  conv_factors:
    include: True
    name: "Conversion factor to gCO2eq m-2 yr-1"
    name_latex: "Conversion factor to gCO$_{2,eq}$ m$^{-2}$ yr$^{-1}$"
    unit: "-"
    unit_latex: "-"
    long_description: ""
...
